import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "")
BOT_MODE = os.getenv("BOT_MODE", "PASSIVE")

AUTO_BAN_THRESHOLD = 0.90
AUTO_MUTE_THRESHOLD = 0.80
AUTO_DELETE_THRESHOLD = 0.70

TARGET_CHATS = []
WHITELIST_AFTER_MESSAGES = 30
